```yaml
api:
  openweather_url: "https://api.openweathermap.org/data/2.5/weather"
  forecast_url: "https://api.openweathermap.org/data/2.5/forecast"
  api_key: "YOUR_API_KEY_HERE"

cities:
  - name: "London"
    lat: 51.5074
    lon: -0.1278
  - name: "New York"
    lat: 40.7128
    lon: -74.0060
  - name: "Tokyo"
    lat: 35.6762
    lon: 139.6503
  - name: "Mumbai"
    lat: 19.0760
    lon: 72.8777

data:
  update_interval: 300  # seconds
  storage_path: "data/"
  
reports:
  output_path: "reports/"
  formats: ["html", "pdf", "json"]
```
